# reference: https://github.com/oblique63/LCTHW-Exercises/blob/master/Makefile
CC=gcc
CFLAGS=-Wall -Wextra -g
FILES = \
	ex01 ex03 ex07 ex08 ex11 ex12 ex13 \
	ex14 ex15 ex16 ex16stackEC ex17 \
	ex18 ex19 ex22 ex30 ex32 ex33 ex34 \
	ex35

all: $(FILES)

clean:
	rm -f $(FILES)

with-clean: clean
	make
